/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FormCadastroAluguelController;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class Cadastroaluguel extends javax.swing.JInternalFrame {
    
    private final FormCadastroAluguelController controller;//criar campo controller em view
    
    public Cadastroaluguel() {
        initComponents();
        //quero que um controller controle a view
        controller = new FormCadastroAluguelController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblDataAluguel = new javax.swing.JLabel();
        jComboBoxVeiculo = new javax.swing.JComboBox<>();
        jLblDataAluguel1 = new javax.swing.JLabel();
        jDateEntrega = new javax.swing.JFormattedTextField();
        jDateAluguel = new javax.swing.JFormattedTextField();
        jLblentregue = new javax.swing.JLabel();
        jLblcliente1 = new javax.swing.JLabel();
        jLblobservacao = new javax.swing.JLabel();
        jTextObservacao = new javax.swing.JTextField();
        jLbId = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jTextEntregue = new javax.swing.JTextField();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConsultar1 = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnCadastrar1 = new javax.swing.JButton();
        jLblvalorpago = new javax.swing.JLabel();
        jTextValorpago = new javax.swing.JTextField();
        jLblveiculo = new javax.swing.JLabel();
        jLblfundo = new javax.swing.JLabel();

        setTitle("Cadastro aluguel");
        getContentPane().setLayout(null);

        jLblDataAluguel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblDataAluguel.setForeground(new java.awt.Color(255, 255, 255));
        jLblDataAluguel.setText("Data aluguel:");
        getContentPane().add(jLblDataAluguel);
        jLblDataAluguel.setBounds(330, 220, 100, 17);

        getContentPane().add(jComboBoxVeiculo);
        jComboBoxVeiculo.setBounds(330, 200, 160, 22);

        jLblDataAluguel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblDataAluguel1.setForeground(new java.awt.Color(255, 255, 255));
        jLblDataAluguel1.setText("Data entrega:");
        getContentPane().add(jLblDataAluguel1);
        jLblDataAluguel1.setBounds(330, 260, 100, 17);
        getContentPane().add(jDateEntrega);
        jDateEntrega.setBounds(330, 280, 160, 22);
        getContentPane().add(jDateAluguel);
        jDateAluguel.setBounds(330, 240, 160, 22);

        jLblentregue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblentregue.setForeground(new java.awt.Color(255, 255, 255));
        jLblentregue.setText("Entregue:");
        getContentPane().add(jLblentregue);
        jLblentregue.setBounds(330, 340, 70, 17);

        jLblcliente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblcliente1.setForeground(new java.awt.Color(255, 255, 255));
        jLblcliente1.setText("Cliente:");
        getContentPane().add(jLblcliente1);
        jLblcliente1.setBounds(330, 300, 60, 17);

        jLblobservacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblobservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLblobservacao.setText("Observação:");
        getContentPane().add(jLblobservacao);
        jLblobservacao.setBounds(330, 380, 90, 17);
        getContentPane().add(jTextObservacao);
        jTextObservacao.setBounds(330, 400, 160, 22);

        jLbId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLbId.setForeground(new java.awt.Color(255, 255, 255));
        jLbId.setText("ID:");
        getContentPane().add(jLbId);
        jLbId.setBounds(330, 140, 70, 17);
        getContentPane().add(jTextId);
        jTextId.setBounds(330, 160, 160, 22);
        getContentPane().add(jTextEntregue);
        jTextEntregue.setBounds(330, 360, 160, 22);

        getContentPane().add(jComboBoxCliente);
        jComboBoxCliente.setBounds(330, 320, 160, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Veiculo", "Data aluguel", "Data entrega", "Cliente", "Entregue", "Observação", "Valor pago"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 42, 560, 460);

        btnConsultar1.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnConsultar1.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar1.setText("CONSULTAR");
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar1);
        btnConsultar1.setBounds(310, 470, 100, 20);

        btnDeletar.setBackground(new java.awt.Color(0, 102, 102));
        btnDeletar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(360, 490, 100, 20);

        btnCadastrar1.setBackground(new java.awt.Color(0, 102, 102));
        btnCadastrar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar1.setText("CADASTRAR");
        btnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar1ActionPerformed(evt);
            }
        });
        btnCadastrar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrar1KeyPressed(evt);
            }
        });
        getContentPane().add(btnCadastrar1);
        btnCadastrar1.setBounds(420, 470, 100, 20);

        jLblvalorpago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblvalorpago.setForeground(new java.awt.Color(255, 255, 255));
        jLblvalorpago.setText("Valor pago:");
        getContentPane().add(jLblvalorpago);
        jLblvalorpago.setBounds(330, 420, 90, 17);
        getContentPane().add(jTextValorpago);
        jTextValorpago.setBounds(330, 440, 160, 22);

        jLblveiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblveiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLblveiculo.setText("Veiculo:");
        getContentPane().add(jLblveiculo);
        jLblveiculo.setBounds(330, 180, 60, 17);

        jLblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/loginn5.png"))); // NOI18N
        getContentPane().add(jLblfundo);
        jLblfundo.setBounds(0, 0, 1170, 510);

        setBounds(0, 0, 1183, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        // TODO add your handling code here:
        //controller
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        //quando clicar no botao chamar o controlador para deletar um aluguel
        //controller
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar1ActionPerformed
        // TODO add your handling code here:
        //quando clicar no botao chamar o controlador para salvar um aluguel
        controller.inserir();
    }//GEN-LAST:event_btnCadastrar1ActionPerformed

    private void btnCadastrar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrar1KeyPressed
        //entrar apertando enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {

            //quando clicar no botao chamar o controlador para salvar um aluguel

        }
        else
        {

            JOptionPane.showMessageDialog(this, "Erro ao inserir cliente!");

        }
    }//GEN-LAST:event_btnCadastrar1KeyPressed
    
    public JTextField getjTextId() {
        return jTextId;
    }

    //metodos getters e setter
    public void setjTextId(JTextField jTextId) {
        this.jTextId = jTextId;
    }

    public JComboBox<Object> getjComboBoxCliente() {
        return jComboBoxCliente;
    }

    public void setjComboBoxCliente(JComboBox<Object> jComboBoxCliente) {
        this.jComboBoxCliente = jComboBoxCliente;
    }

    public JComboBox<Object> getjComboBoxVeiculo() {
        return jComboBoxVeiculo;
    }

    public void setjComboBoxVeiculo(JComboBox<Object> jComboBoxVeiculo) {
        this.jComboBoxVeiculo = jComboBoxVeiculo;
    }

    public JFormattedTextField getjDateAluguel() {
        return jDateAluguel;
    }

    public void setjDateAluguel(JFormattedTextField jDateAluguel) {
        this.jDateAluguel = jDateAluguel;
    }

    public JFormattedTextField getjDateEntrega() {
        return jDateEntrega;
    }

    public void setjDateEntrega(JFormattedTextField jDateEntrega) {
        this.jDateEntrega = jDateEntrega;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjTextEntregue() {
        return jTextEntregue;
    }

    public void setjTextEntregue(JTextField jTextEntregue) {
        this.jTextEntregue = jTextEntregue;
    }

    public JTextField getjTextObservacao() {
        return jTextObservacao;
    }

    public void setjTextObservacao(JTextField jTextObservacao) {
        this.jTextObservacao = jTextObservacao;
    }

    public JTextField getjTextValorpago() {
        return jTextValorpago;
    }

    public void setjTextValorpago(JTextField jTextValorpago) {
        this.jTextValorpago = jTextValorpago;
    }
          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JComboBox<Object> jComboBoxCliente;
    private javax.swing.JComboBox<Object> jComboBoxVeiculo;
    private javax.swing.JFormattedTextField jDateAluguel;
    private javax.swing.JFormattedTextField jDateEntrega;
    private javax.swing.JLabel jLbId;
    private javax.swing.JLabel jLblDataAluguel;
    private javax.swing.JLabel jLblDataAluguel1;
    private javax.swing.JLabel jLblcliente1;
    private javax.swing.JLabel jLblentregue;
    private javax.swing.JLabel jLblfundo;
    private javax.swing.JLabel jLblobservacao;
    private javax.swing.JLabel jLblvalorpago;
    private javax.swing.JLabel jLblveiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextEntregue;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextObservacao;
    private javax.swing.JTextField jTextValorpago;
    // End of variables declaration//GEN-END:variables
}
