/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FormCadastroclienteController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class Cadastrocliente extends javax.swing.JInternalFrame {

    private final FormCadastroclienteController controller;//criar campo controller em view
    
    public Cadastrocliente() {
        initComponents();
        //adicionar controlador a view
        controller = new FormCadastroclienteController(this);//criar campo controller em view
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextEndereco = new javax.swing.JTextField();
        jTextNome1 = new javax.swing.JTextField();
        jLblNome = new javax.swing.JLabel();
        jLblEndereco = new javax.swing.JLabel();
        jLbUF = new javax.swing.JLabel();
        jTextTelefone = new javax.swing.JTextField();
        jTextUF1 = new javax.swing.JTextField();
        jLblTelefone = new javax.swing.JLabel();
        jLblCPF = new javax.swing.JLabel();
        jTextCPF = new javax.swing.JTextField();
        jLblEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        btnConsultar1 = new javax.swing.JButton();
        btnCadastrar1 = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Cadastro cliente");
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereco", "UF", "Telefone", "CPF", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 30, 520, 420);

        jTextEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEnderecoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextEndereco);
        jTextEndereco.setBounds(250, 220, 160, 22);

        jTextNome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNome1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextNome1);
        jTextNome1.setBounds(250, 180, 160, 22);

        jLblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblNome.setForeground(new java.awt.Color(255, 255, 255));
        jLblNome.setText("Nome:");
        getContentPane().add(jLblNome);
        jLblNome.setBounds(250, 160, 60, 17);

        jLblEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jLblEndereco.setText("Endereco:");
        getContentPane().add(jLblEndereco);
        jLblEndereco.setBounds(250, 200, 80, 17);

        jLbUF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLbUF.setForeground(new java.awt.Color(255, 255, 255));
        jLbUF.setText("UF:");
        getContentPane().add(jLbUF);
        jLbUF.setBounds(250, 240, 60, 17);

        jTextTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextTelefoneKeyPressed(evt);
            }
        });
        getContentPane().add(jTextTelefone);
        jTextTelefone.setBounds(250, 300, 160, 22);

        jTextUF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextUF1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextUF1);
        jTextUF1.setBounds(250, 260, 160, 22);

        jLblTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLblTelefone.setText("Telefone:");
        getContentPane().add(jLblTelefone);
        jLblTelefone.setBounds(250, 280, 70, 17);

        jLblCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLblCPF.setText("CPF:");
        getContentPane().add(jLblCPF);
        jLblCPF.setBounds(250, 320, 60, 17);

        jTextCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCPFKeyPressed(evt);
            }
        });
        getContentPane().add(jTextCPF);
        jTextCPF.setBounds(250, 340, 160, 22);

        jLblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLblEmail.setText("Email:");
        getContentPane().add(jLblEmail);
        jLblEmail.setBounds(250, 360, 60, 17);

        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEmailKeyPressed(evt);
            }
        });
        getContentPane().add(jTextEmail);
        jTextEmail.setBounds(250, 380, 160, 22);

        btnConsultar1.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnConsultar1.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar1.setText("CONSULTAR");
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });
        btnConsultar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConsultar1KeyPressed(evt);
            }
        });
        getContentPane().add(btnConsultar1);
        btnConsultar1.setBounds(230, 410, 100, 20);

        btnCadastrar1.setBackground(new java.awt.Color(0, 102, 102));
        btnCadastrar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar1.setText("CADASTRAR");
        btnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar1ActionPerformed(evt);
            }
        });
        btnCadastrar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrar1KeyPressed(evt);
            }
        });
        getContentPane().add(btnCadastrar1);
        btnCadastrar1.setBounds(340, 410, 100, 20);

        btnDeletar.setBackground(new java.awt.Color(0, 102, 102));
        btnDeletar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        btnDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeletarKeyPressed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(280, 430, 100, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/loginn2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1004, 456);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEnderecoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {

            jTextTelefone.requestFocus();

        }
    }//GEN-LAST:event_jTextEnderecoKeyPressed

    private void jTextTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefoneKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {

            jTextTelefone.requestFocus();

        }
    }//GEN-LAST:event_jTextTelefoneKeyPressed

    private void jTextCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCPFKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {

            jTextEmail.requestFocus();

        }
    }//GEN-LAST:event_jTextCPFKeyPressed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void btnConsultar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConsultar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar1KeyPressed

    private void btnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrar1ActionPerformed

    private void btnCadastrar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrar1KeyPressed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        //quando clicar no botao chamar o controlador para salvar um usuario
        controller.inserir();

    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnDeletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeletarKeyPressed
        //entrar apertando enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {

            //quando clicar no botao chamar o controlador para salvar um usuario
            controller.inserir();

        }
        else
        {

            JOptionPane.showMessageDialog(this, "Usuario e/ou senha invalidos!");

        }
    }//GEN-LAST:event_btnDeletarKeyPressed

    private void jTextNome1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNome1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {

            jTextEndereco.requestFocus();

        }
    }//GEN-LAST:event_jTextNome1KeyPressed

    private void jTextEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {

            btnCadastrar1.requestFocus();

        }
    }//GEN-LAST:event_jTextEmailKeyPressed

    private void jTextUF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUF1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUF1KeyPressed

    //metodos getters e setter
    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjTextCPF() {
        return jTextCPF;
    }

    public void setjTextCPF(JTextField jTextCPF) {
        this.jTextCPF = jTextCPF;
    }

    public JTextField getjTextEmail() {
        return jTextEmail;
    }

    public void setjTextEmail(JTextField jTextEmail) {
        this.jTextEmail = jTextEmail;
    }

    public JTextField getjTextEndereco() {
        return jTextEndereco;
    }

    public void setjTextEndereco(JTextField jTextEndereco) {
        this.jTextEndereco = jTextEndereco;
    }

    public JTextField getjTextNome1() {
        return jTextNome1;
    }

    public void setjTextNome1(JTextField jTextNome1) {
        this.jTextNome1 = jTextNome1;
    }

    public JTextField getjTextTelefone() {
        return jTextTelefone;
    }

    public void setjTextTelefone(JTextField jTextTelefone) {
        this.jTextTelefone = jTextTelefone;
    }

    public JTextField getjTextUF1() {
        return jTextUF1;
    }

    //metodos getters e setter
    public void setjTextUF1(JTextField jTextUF1) {
        this.jTextUF1 = jTextUF1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbUF;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEndereco;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextNome1;
    private javax.swing.JTextField jTextTelefone;
    private javax.swing.JTextField jTextUF1;
    // End of variables declaration//GEN-END:variables
}
