/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FormCadastrologinController;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class Cadastrologin extends javax.swing.JInternalFrame {

    private final FormCadastrologinController controller; //criar campo controller em view

    /**
     * Creates new form Cadastrologin
     */
    public Cadastrologin() {
        initComponents();
        //adicionar controlador a view
        controller = new FormCadastrologinController(this); //criar campo controller em view
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextSenha = new javax.swing.JPasswordField();
        jLblCargo = new javax.swing.JLabel();
        jComboCargo = new javax.swing.JComboBox<>();
        jTextLogin = new javax.swing.JTextField();
        jLblLogin = new javax.swing.JLabel();
        jLblSenha = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLblfundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Cadastro login");
        getContentPane().setLayout(null);

        jLblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblNome.setForeground(new java.awt.Color(255, 255, 255));
        jLblNome.setText("Nome:");
        getContentPane().add(jLblNome);
        jLblNome.setBounds(310, 150, 60, 17);

        jTextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomeKeyPressed(evt);
            }
        });
        getContentPane().add(jTextNome);
        jTextNome.setBounds(310, 170, 160, 22);

        jTextSenha.setText("jPasswordField1");
        jTextSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jTextSenha);
        jTextSenha.setBounds(310, 290, 160, 22);

        jLblCargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblCargo.setForeground(new java.awt.Color(255, 255, 255));
        jLblCargo.setText("Cargo:");
        getContentPane().add(jLblCargo);
        jLblCargo.setBounds(310, 190, 60, 17);

        jComboCargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Cliente" }));
        jComboCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboCargoKeyPressed(evt);
            }
        });
        getContentPane().add(jComboCargo);
        jComboCargo.setBounds(310, 210, 160, 22);

        jTextLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextLoginKeyPressed(evt);
            }
        });
        getContentPane().add(jTextLogin);
        jTextLogin.setBounds(310, 250, 160, 22);

        jLblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLblLogin.setText("Login:");
        getContentPane().add(jLblLogin);
        jLblLogin.setBounds(310, 230, 60, 17);

        jLblSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLblSenha.setText("Senha:");
        getContentPane().add(jLblSenha);
        jLblSenha.setBounds(310, 270, 60, 17);

        jLblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLblEmail.setText("Email:");
        getContentPane().add(jLblEmail);
        jLblEmail.setBounds(310, 310, 60, 17);

        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEmailKeyPressed(evt);
            }
        });
        getContentPane().add(jTextEmail);
        jTextEmail.setBounds(310, 330, 160, 22);

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 102));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarKeyPressed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(340, 370, 100, 20);

        jLblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/loginn.png"))); // NOI18N
        getContentPane().add(jLblfundo);
        jLblfundo.setBounds(0, 0, 570, 430);

        setBounds(0, 0, 567, 456);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        //quando clicar no botao chamar o controlador para salvar um usuario
        controller.inserir();
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jComboCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboCargoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {
            
            jTextLogin.requestFocus();
            
        }          
    }//GEN-LAST:event_jComboCargoKeyPressed

    private void jTextNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {
            
            jComboCargo.requestFocus();
            
        }  
    }//GEN-LAST:event_jTextNomeKeyPressed

    private void jTextLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLoginKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {
            
            jTextSenha.requestFocus();
            
        }
    }//GEN-LAST:event_jTextLoginKeyPressed

    private void jTextSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSenhaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {
            
            jTextEmail.requestFocus();
            
        }
    }//GEN-LAST:event_jTextSenhaKeyPressed

    private void jTextEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)//ao pressionar botao enter peça o foco
        {
            
            btnCadastrar.requestFocus();
            
        }
    }//GEN-LAST:event_jTextEmailKeyPressed

    private void btnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarKeyPressed
        //entrar apertando enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            
	//quando clicar no botao chamar o controlador para salvar um usuario
        controller.inserir();            
            
        }
        else
        {
            
            JOptionPane.showMessageDialog(this, "Usuario e/ou senha invalidos!");
            
        }
    }//GEN-LAST:event_btnCadastrarKeyPressed

    //metodos getters e setters da view
    
    public JComboBox<String> getjComboCargo() {
        return jComboCargo;
    }

    public void setjComboCargo(JComboBox<String> jComboCargo) {
        this.jComboCargo = jComboCargo;
    }

    public JTextField getjTextEmail() {
        return jTextEmail;
    }

    public void setjTextEmail(JTextField jTextEmail) {
        this.jTextEmail = jTextEmail;
    }

    public JTextField getjTextLogin() {
        return jTextLogin;
    }

    public void setjTextLogin(JTextField jTextLogin) {
        this.jTextLogin = jTextLogin;
    }

    public JTextField getjTextNome() {
        return jTextNome;
    }

    public void setjTextNome(JTextField jTextNome) {
        this.jTextNome = jTextNome;
    }

    public JPasswordField getjTextSenha() {
        return jTextSenha;
    }

    public void setjTextSenha(JPasswordField jTextSenha) {
        this.jTextSenha = jTextSenha;
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> jComboCargo;
    private javax.swing.JLabel jLblCargo;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblLogin;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JLabel jLblfundo;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JPasswordField jTextSenha;
    // End of variables declaration//GEN-END:variables
}
